spring.application.name=ai-agent-gemini
server.port=8080

# LangChain4j Google Gemini Configuration
langchain4j.google-ai.gemini.chat-model.api-key=
langchain4j.google-ai.gemini.chat-model.model-name=gemini-2.0-flash
langchain4j.google-ai.gemini.chat-model.temperature=0.7
langchain4j.google-ai.gemini.chat-model.log-requests-and-responses=true


# 3. Vector DB Configuration (Connecting to pgvector)
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_database
spring.datasource.username=hr_admin
spring.datasource.password=hr_password